config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#new'

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  attr_accessor :avatar_file
  validates :username,
              format: {with: /\A[a-zA-z0-9_@.]+\z/, message: 'ne peut contenir que des caracteres alphanumerique et "_@.".'},
              length: {in: 4...20, too_short: 'nombre de caracteres minimum : 4.', too_long: 'nombre de caracteres maximum : 20.'},
              uniqueness: {case_sensitive: false, message: "ce nom d'utilisateur est deja pris."}
  validates :email,
              format: {with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/, message: "format d'email invalide."},
              uniqueness: {case_sensitive: false, message: "cette email est deja pris."}
  validates :avatar_file,
              file: {ext: [:jpg, :png, :jpeg]}


  def to_session
    {id: id}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :only_signed_in
  add_flash_types :success, :danger
  helper_method :current_user, :user_signed_in?

  private

  def only_signed_in
    if !user_signed_in?
      redirect_to new_user_path, danger: 'vous devez etre conneter pour acceder a cette page !'
    end
  end

  def only_signed_out
    if user_signed_in?
      redirect_to profil_path
    end
  end

  def user_signed_in?
    current_user ? true : false
  end

  def current_user
    return nil if !session[:auth] or !session[:auth]['id']
    return @_user if @_user
    @_user =  User.find_by_id(session[:auth]['id'])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create]
  before_action :only_signed_out, only: [:new, :create]

  def new
    @user = User.new

  end

  def create
    user_params = params.require(:user)
    @user = User.where(username: user_params[:username]).or(User.where(email: user_params[:username])).first
    if @user and @user.authenticate(user_params[:password])
      session[:auth] = @user.to_session
      redirect_to profil_path, success: 'Connection reussi !'
    else
      redirect_to new_session_path, danger: 'Identifiants incorrects'
    end
  end

  def destroy
    if session[:auth] and session[:auth]['id']
      session.destroy
    end
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  skip_before_action :only_signed_in, only: [:new, :create]
  before_action :only_signed_out, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:username, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:auth] = @user.to_session
      redirect_to profil_path, success: 'Votre compte a bien ete cree !'
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    user_params = params.require(:user).permit(:username, :email, :firstname, :lastename, :avatar_file)
    if @user.update(user_params)
      redirect_to profil_path, success: 'Votre compte a ete mis a jour !'
    else
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beryl</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Beryl</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <% if current_user %>
              <div class="navbar-nav navbar-right">
                <div class="dropdown">
                  <button class="btn btn-success bg-inverse dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Profile
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="<%= profil_path %>">Mon profil</a>
                    <a class="dropdown-item" href="<%= destroy_session_path %>" data-method="delete">Se deconnecter</a>
                  </div>
                </div>
              </div>
          <% else %>
              <ul class="navbar-nav justify-content-end">
                <li class="nav-item">
                  <a class="nav-link" href="<%= new_session_path%>">Connection</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%= new_user_path %>">Inscription</a>
                </li>
              </ul>
          <% end%>
        </div>
      </div>
    </nav>

    <div class="container" style="margin-top: 3rem">

      <% if flash[:success] %>
          <div class="alert alert-success">
            <%= flash[:success] %>
          </div>
      <% end %>
      <% if flash[:danger] %>
          <div class="alert alert-danger">
            <%= flash[:danger] %>
          </div>
      <% end %>
      <%= yield %>
    </div>


    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @user.errors.full_messages.each do |error| %>
            <li>
              <strong><%= error %></strong>
            </li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="card">
  <div class="card-header">Editer</div>
  <div class="card-block">
    <%=	 form_for @user,url: profil_path, html: {class: 'form-horizontal'} do |f| %>
        <div class="from-inline">
          <%= f.label :avatar_file, "Avatar" %>
          <%= f.file_field :avatar_file, class: 'form-control col-6' %>
        </div>
        <div class="from-inline">
          <%= f.label :username, "Nom d'utilisateur" %>
          <%= f.text_field :username, class: 'form-control col-6' %>
        </div>
        <div class="from-group">
          <%= f.label :email, "Email" %>
          <%= f.email_field :email, class: 'form-control col-6' %>
        </div>
        <div class="from-group">
          <%= f.label :firstname, "Prenom" %>
          <%= f.text_field :firstname, class: 'form-control col-6' %>
        </div>
        <div class="from-group">
          <%= f.label :lastname, "Nom de famile" %>
          <%= f.text_field :lastname, class: 'form-control col-6' %>
        </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 1rem">S'inscrire</button>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @user.errors.full_messages.each do |error| %>
          <li>
            <strong><%= error %></strong>
          </li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="card">
  <div class="card-header">S'inscrire</div>
  <div class="card-block">
    <%=	 form_for @user, {class: 'form-horizontal'} do |f| %>
      <div class="from-group">
        <%= f.label :username, "Nom d'utilisateur" %>
        <%= f.text_field :username, class: 'form-control col-6' %>
      </div>
      <div class="from-group">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: 'form-control col-6' %>
      </div>
      <div class="from-group">
        <%= f.label :password, "Mot de passe" %>
        <%= f.password_field :password, class: 'form-control col-6' %>
      </div>
      <div class="from-group">
        <%= f.label :password_confirmation, "Confirmation du mot de passe" %>
        <%= f.password_field :password_confirmation, class: 'form-control col-6' %>
      </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 1rem">S'inscrire</button>
    <% end %>
  </div>
</div>